name: just-storage
region: nyc

services:
  - name: just-storage
    github:
      repo: yourusername/just_storage
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    docker_build_context: .
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    routes:
      - path: /
    envs:
      - key: RUST_LOG
        value: info
      - key: GC_INTERVAL_SECS
        value: "60"
      - key: GC_BATCH_SIZE
        value: "100"
      - key: HOT_STORAGE_ROOT
        value: /app/data/hot
      - key: COLD_STORAGE_ROOT
        value: /app/data/cold
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: API_KEYS
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

databases:
  - name: just-storage-db
    engine: PG
    production: false
    version: "15"
    db_name: just_storage
    db_user: just_storage
