name: Docker Build

on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ gitea.workflow }}-${{ gitea.event_name }}-${{ gitea.ref }}
  cancel-in-progress: true

env:
  REGISTRY: registry.bk.glpx.pro
  IMAGE: registry.bk.glpx.pro/just-storage/just-storage

jobs:
  docker:
    uses: mukimovd/.github/.gitea/workflows/docker-ci.yml@main
    with:
      image-name: just-storage/just-storage
    secrets: inherit
